# Generated by Django 6.0 on 2025-12-13 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clé de session')),
                ('intent', models.CharField(choices=[('greeting', 'Salutation'), ('product_info', 'Information sur le produit'), ('order_status', 'Statut de commande'), ('delivery_info', 'Information de livraison'), ('payment_info', 'Information de paiement'), ('complaint', 'Réclamation'), ('thanks', 'Remerciement'), ('goodbye', 'Au revoir'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Intention')),
                ('user_message', models.TextField(verbose_name="Message de l'utilisateur")),
                ('bot_response', models.TextField(verbose_name='Réponse du bot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('requires_followup', models.BooleanField(default=False, verbose_name='Suivi requis')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='chatbot_con_user_id_81f32d_idx'), models.Index(fields=['session_key'], name='chatbot_con_session_b87ccc_idx'), models.Index(fields=['intent'], name='chatbot_con_intent_4a9187_idx'), models.Index(fields=['created_at'], name='chatbot_con_created_e6d9d9_idx')],
            },
        ),
    ]
