# Generated by Django 6.0 on 2025-12-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('retrait', 'Retrait en magasin'), ('livraison', 'Livraison à domicile')], default='retrait', max_length=20, verbose_name='Type de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, help_text='Remplir uniquement pour une livraison à domicile', max_length=250, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('lumicash', 'Lumicash'), ('ecocash', 'EcoCash'), ('ihela', 'Ihela')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
    ]
