# Generated by Django 6.0 on 2025-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_type_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paiement_magasin', 'Paiement en magasin'), ('lumicash', 'Lumicash'), ('ecocash', 'EcoCash'), ('ihela', 'Ihela')], max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
