# Generated by Django 6.0 on 2025-12-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('lumicash', 'Lumicash'), ('ecocash', 'EcoCash'), ('ihela', 'Ihela')], max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
