# Generated by Django 6.0 on 2025-12-13 18:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantité à ajouter au stock (négative pour retirer)', verbose_name='Quantité')),
                ('date_entree', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'entrée")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Entrée en stock',
                'verbose_name_plural': 'Entrées en stock',
                'ordering': ['-date_entree'],
            },
        ),
    ]
