# Generated by Django 6.0 on 2025-12-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date_entree'], 'verbose_name': 'Mouvement de stock', 'verbose_name_plural': 'Mouvements de stock'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Le produit est-il disponible à la vente ?', verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Quantité à ajouter au stock (positive pour ajouter, négative pour retirer)', verbose_name='Quantité'),
        ),
    ]
