# Generated by Django 6.0 on 2025-12-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_update_product_slugs'),
        ('products', '0003_alter_stock_options_remove_product_stock_and_more'),
    ]

    operations = [
    ]
