# Generated by Django 6.0 on 2025-12-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
